### ISSUE TITLE
update farm account request information

### ISSUE THREAD

**Issue by bluegenes** [dib-lab/farm-notes#60]
The link for creating a new farm account has shifted to the HiPPO ("High Performance Personnel Onboarding") system, and should be updated on the [Getting Started](https://github.com/dib-lab/farm-notes/blob/latest/getting-started.md) page.

direct farm link: https://hippo.ucdavis.edu/Farm/create 

Or, https://hpc.ucdavis.edu/hippo and then follow the 'Farm' link

**Comment by ctb** [comment]
done in https://github.com/dib-lab/farm-notes/pull/61
